/*
 * File: app/model/FilterModel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvolveQueryEditor.model.FilterModel', {
    extend: 'Ext.data.Model',
    idgen: 'sequential',
    idProperty: 'id',

    uses: [
        'EvolveQueryEditor.model.FilterValueModel'
    ],

    hasOne: {
        associationKey: 'Value',
        model: 'EvolveQueryEditor.model.FilterValueModel',
        setterName: 'setValue',
        getterName: 'getValue'
    },
    fields: [
        {
            name: 'single'
        },
        {
            name: 'name'
        },
        {
            name: 'from',
            defaultValue: undefined
        },
        {
            name: 'to'
        },
        {
            name: 'codePath'
        },
        {
            name: 'dataType'
        },
        {
            name: 'lookupCategory'
        },
        {
            name: 'allowSegments'
        },
        {
            name: 'allowMultipleFilters'
        },
        {
            name: 'hasValue',
            type: 'boolean',
            defaultValue: false
        },
        {
            name: 'operator',
            defaultValue: 1 // IS_EQUAL
        },
        {
            name: 'mode',
            defaultValue: 0 // DEFAULT
        },
        {
            name: 'caseSens',
            type: 'boolean',
            defaultValue: false
        },
        {
            name: 'segment',
            type: 'boolean',
            defaultValue: false
        },
        {
            name: 'segmentOffset',
            defaultValue: 0
        },
        {
            name: 'segmentLength',
            defaultValue: 0
        },
        {
            name: 'superFieldFilter',
            type: 'boolean',
            defaultValue: false
        },
]
});