/*
 * File: app/store/JsonPostingProxy.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvolveQueryEditor.store.JsonPostingProxy', {
    extend: 'Ext.data.AjaxProxy',
    alias: 'store.JsonPostingProxy',

    buildRequest: function(operation) {
        var request = this.callParent(arguments); 

        request.jsonData = this.extraParams; 
        this.extraParams = {};

        return request; 
    },

    getMethod: function(request) {
        return 'POST';
    }
});