/*
 * File: app/store/ReportTypeStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvolveQueryEditor.store.ReportTypeStore', {
    extend: 'Ext.data.Store',
    model: 'EvolveQueryEditor.model.ReportTypeModel',
    
    statics: {
        create: function(dialogContainer) {
            var store =  Ext.create('EvolveQueryEditor.store.ReportTypeStore');
            
            //This is kinda ugly because the summaryReport and detailReport are supposed to be readoly singleton objects and their properties should not
            //be modified. However 'TypeImage' depends on external resource so here it is a compromise to set this property
            var summaryReport = EvolveQueryEditor.model.ReportTypeModel.SummaryReport;
            summaryReport.set('TypeImage', dialogContainer.getResourceUrl('Content/summary-report.png'));
            var detailReport = EvolveQueryEditor.model.ReportTypeModel.DetailReport;
            detailReport.set('TypeImage', dialogContainer.getResourceUrl('Content/detail-report.png'));
            
            store.add(summaryReport);
            store.add(detailReport);
            
            return store;
        }
    } 
    
});