/*
 * File: app/store/ReportTypeStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvolveQueryEditor.store.ScalingFactorStore', {
    extend: 'Ext.data.Store',
    model: 'EvolveQueryEditor.model.ScalingFactorModel',
}, function(Cls) {
     Cls.Instance =  Ext.create('EvolveQueryEditor.store.ScalingFactorStore');
     
     Cls.Instance.add(EvolveQueryEditor.model.ScalingFactorModel.DividedBy10);
     Cls.Instance.add(EvolveQueryEditor.model.ScalingFactorModel.DividedBy100);
     Cls.Instance.add(EvolveQueryEditor.model.ScalingFactorModel.DividedBy1000);
     Cls.Instance.add(EvolveQueryEditor.model.ScalingFactorModel.DividedBy10000);
     Cls.Instance.add(EvolveQueryEditor.model.ScalingFactorModel.DividedBy100000);
     Cls.Instance.add(EvolveQueryEditor.model.ScalingFactorModel.DividedBy1000000);
     Cls.Instance.add(EvolveQueryEditor.model.ScalingFactorModel.DividedBy10000000);
});