/*
 * File: app/view/EvolveProgressDialog.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EvolveQueryEditor.view.EvolveProgressDialog', {
    extend: 'Ext.window.Window',

    singleton: true,

    height: 100,
    width: 389,
    layout: {
        align: 'middle',
        pack: 'center',
        type: 'hbox'
    },
    frameHeader: false,
    header: false,
    title: 'Connecting to Evolve ...',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'label',
                    id: 'progressCaption',
                    itemId: 'progressCaption',
                    style: 'font-size: x-large',
                    text: ''
                }
            ],
            listeners: {
                show: {
                    fn: me.onWindowShow,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onWindowShow: function(component, eOpts) {
        //Ext.WindowManager.bringToFront(this);

    },

    SetProgressText: function(caption) {
        this.down('#progressCaption').text = caption;
    }

});